name: 'Upload Coverage'
description: 'Uploads code coverage reports to codecov with separate flags for separate packages'
runs:
  using: 'composite'
  steps:
    - name: Upload Core Coverage
      uses: codecov/codecov-action@v3
      with:
        files: ./packages/core/coverage/coverage-final.json
        flags: core
