name: Build Tests
on:
  push:
    branches:
      - 'main'
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          run_install: true
      #      - name: Get pnpm store directory
      #        id: pnpm-cache
      #        shell: bash
      #        run: |
      #          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      #      - uses: actions/cache@v3
      #        name: Setup pnpm cache
      #        with:
      #          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
      #          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
      #          restore-keys: |
      #            ${{ runner.os }}-pnpm-store-
      #      - name: Install dependencies
      #        run: pnpm install

      - name: ESLint (PR)
        if: ${{ github.event_name != 'push' }}
        run: pnpm lint --filter="...[origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'main' }}]"

      - name: ESLint (Push)
        if: ${{ github.event_name == 'push' }}
        run: pnpm lint --filter="...[HEAD^1]"

      - name: Format (PR)
        if: ${{ github.event_name != 'push' }}
        run: pnpm format:check --filter="...[origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'main' }}]"

      - name: Format (Push)
        if: ${{ github.event_name == 'push' }}
        run: pnpm format:check --filter="...[HEAD^1]"

      - name: Build dependencies (PR)
        if: ${{ github.event_name != 'push' }}
        run: pnpm build --filter="...[origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'main' }}]"

      - name: Build dependencies (Push)
        if: ${{ github.event_name == 'push' }}
        run: pnpm build --filter="...[HEAD^1]"

      - name: Tests (PR)
        if: ${{ github.event_name != 'push' }}
        run: pnpm test:cov --filter="...[origin/${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || 'main' }}]"

      - name: Tests (Push)
        if: ${{ github.event_name == 'push' }}
        run: pnpm test:cov --filter="...[HEAD^1]"

      - name: Upload Coverage
        uses: ./.github/workflows/code_coverage
